#!/bin/sh


eval last=\${$#}
if [ -f "$last" ]; then
	file="$last"
fi
cat ${file:-/dev/stdin} > "${TMP}/bflmpsvz"
file="${TMP}/bflmpsvz"
if [ "$1" = "-l" -o "$1" = "--lines" ]; then
	start=`echo $2 | cut -d- -f1`
	end=`echo $2 | cut -d- -f2`
	if [ "$start" -gt "$end" ]; then
		echo "M was greater then N"
	fi
elif [ "$1" = "-f" -o "$1" = "--fraction" ]; then
	A=`echo $2 | cut -d/ -f1`
	B=`echo $2 | cut -d/ -f2`
	C=`echo $3 | cut -d/ -f1`
	D=`echo $3 | cut -d/ -f2`
	N=`cat $file | wc -l`
	start=`expr $N \* $A`
	start=`expr $start / $B`
	end=`expr $N \* $C`
	reminder=`expr $end % $D`
	end=`expr $end / $D`
	if [ $reminder -gt 0 ]; then
		end=`expr $end + 1`
	fi
elif [ "$1" = "-p" -o "$1" = "--part" ]; then
	A=`echo $2 | cut -d/ -f1`
	B=`echo $2 | cut -d/ -f2`
	N=`cat $file | wc -l`
	increment=`expr $N / $B`
	end=`expr $A \* $increment`
	start=`expr $end - $increment + 1`
else
	echo 'Unknown option: '$1'!'
fi

index=1
while read line
do
	if [ "$index" -ge "$start" -a "$index" -le "$end" ]; then
		echo $line
	fi
	index=`expr $index + 1`
done < "$file"

rm $file
exit 0
